services:
  sandbox:
    image: wxhere/bitcomet-webui:v2.15.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    environment:
      - TZ=${TIME_ZONE}
      - BITCOMET_WEBUI_PORT=${PANEL_APP_PORT_HTTP}
      - BITCOMET_BT_PORT=${PANEL_TORRENTING_PORT}
      - WEBUI_USERNAME=${PANEL_BITCOMET_USERNAME}
      - WEBUI_PASSWORD=${PANEL_BITCOMET_PASSWORD}
    ports:
      - ${PANEL_TORRENTING_PORT}:${PANEL_TORRENTING_PORT}
      - ${PANEL_TORRENTING_PORT}:${PANEL_TORRENTING_PORT}/udp
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    volumes:
      # 将容器中的配置文件目录映射到主机目录中
      - ./config:/root/.config/BitComet:rw
      # 将容器中的下载目录映射到主机目录中
      - ./data:/root/Downloads:rw
    labels:
      createdBy: 'Apps'
networks:
  1panel-network:
    external: true
