services:
  gitea-copilot:
    image: ghcr.io/kekxv/gitea-copilot:v0.1.6
    volumes:
      - ./data:/app/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:8000
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
